name: "NGCC tuning CI workflow"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        angular-version:
          - 9.0.x
          - 9.1.x
          - 10.0.x
          - 10.1.x
          - 10.2.x
          - 11.0.x
          - 11.1.x
          - 11.2.x
        ngcc-property:
          - fesm2015
          - esm2015
          - es2015
          - browser
          - module
          - main
        ngcc-create-ivy-entry-points:
          - true
          - false

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: ngworker/angular-versions-action@v3
        with:
          angular-version: ${{ matrix.angular-version }}

      - run: npm install --global pnpm
      - run: pnpm install --frozen-lockfile false --verify-store-integrity false

      - run: pnpx ngcc --first-only --properties ${{ matrix.ngcc-property }} es2015 browser module main --create-ivy-entry-points
        if: matrix.ngcc-create-ivy-entry-points == true
      - run: pnpx ngcc --first-only --properties ${{ matrix.ngcc-property }} es2015 browser module main
        if: matrix.ngcc-create-ivy-entry-points == false

      - run: pnpm build
