name: "NGCC tuning CI workflow"

env:
  NODE_LATEST: 12.x
  NODE_OPTIONS: --max_old_space_size=6144

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        angular-version:
          - 9.0.x
          - 9.1.x
          - 10.0.x
          - 10.1.x
          - 10.2.x
          - 11.0.x
          - 11.1.x
          - 11.2.x
        ngcc-properties:
          - es2015 module browser main
          - module browser main

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_LATEST }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_LATEST }}
      - uses: ngworker/angular-versions-action@v3
        with:
          angular-version: ${{ matrix.angular-version }}

      - run: yarn install --non-interactive --silent

      - run: npx ngcc --first-only --properties ${{ matrix.ngcc-properties }} --create-ivy-entry-points

      - run: yarn build
